student_record:main.o stud_add.o stud_show.o stud_del.o stud_save.o stud_del_all.o rev_rec.o stud_modify.o stud_sort.o
	cc main.c stud_add.c stud_show.c stud_del.c stud_save.c stud_del_all.c rev_rec.c stud_modify.c stud_sort.c -o student_record
main.o:main.c
	cc -c main.c
stud_add.o: stud_add.c
	cc -c stud_add.c
stud_show.o: stud_show.c
	cc -c stud_show.c
stud_del.o: stud_del.c
	cc -c stud_del.c
stud_save.o: stud_save.c
	cc -c stud_save.c
stud_del_all.o: stud_del_all.c
	cc -c stud_del_all.c
rev_rec.o: rev_rec.c
	cc -c rev_rec.c
stud_modify.o: stud_modify.c
	cc -c stud_modify.c
stud_sort.o: stud_sort.c
	cc -c stud_sort.c
